CREATE TABLE IF NOT EXISTS STUDENT(
  ROLL_NO TEXT PRIMARY KEY,
  NAME TEXT,
  ADDRESS TEXT,
  PHONE TEXT,
  AGE TEXT
);
INSERT INTO STUDENT(ROLL_NO,NAME,ADDRESS,PHONE,AGE)
VALUES
  ("1","RAM","DELHI","*****","18"),
  ("2","RAMESH","GURGAO","*****","18"),
  ("3","SUJIT","ROHTAK","*****","20"),
  ("4","SURESH","DELHI","*****","18"),
  ("5","AMAN","ROHTAK","*****","20"),
  ("6","HARSH","GURGAO","*****","18");

SELECT * FROM Salesman;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';
SELECT * FROM Student WHERE NAME = 'Ram' OR NAME = 'SUJIT';
SELECT * FROM Student WHERE NAME = 'Ram' OR Age = 20;
SELECT * FROM Student WHERE Age = 18 AND (NAME = 'Ram' OR NAME = 'RAMESH');