CREATE TABLE IF NOT EXISTS NOBEL_WIN(
  YEAR TEXT,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT
);
INSERT INTO NOBEL_WIN(YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY)
VALUES
  ("1970","PHYSICS","HANNES ALFVEN","SWEDEN","SCIENTIST"),
  ("1970","PHYSICS","LOUIS NEEL","FRANCE","SCIENTIST"),
  ("1971","PHYSICS","PAUL","FRANCE","SCIENTIST"),
  ("1971","CHEMISTERY","HAMILTON","SWEDEN","LINGUIST"),
  ("1972","LITERATURE","BERNARD KELSON","GERMANY","ECONOMIST"),
  ("1972","ECONOMICS","JOSEPH","RUSSIA","ECONOMICS"),
  ("1973","BIOLOGY","PHILIPS","USA","PRIME MINISTER"),
  ("1980","BIOLOGY","MARTIN","USA","PRESIDENT"),
  ("1981","PHYSIOLOGY","HANNAH","HUNGARY","SCIENTIST"),
  ("1975","PHYSICS","PETER","CHILE","SCIENTIST");

SELECT * 
 FROM nobel_win 
  WHERE subject NOT LIKE 'P%' 
   ORDER BY year DESC, winner;